select * from film;
select * from rental;
select * from category;
select * from store;


----------------------------------------------------------------------------------------------------------------
--- Customer and Cities they Live In
select concat(first_name,' ',last_name) as full_name, city
from customer c
join address a using (address_id)
join city ci using (city_id);

----------------------------------------------------------------------------------------------------------------
--- Total Number of Films Rented by each Customer
select concat(first_name,' ',last_name) as full_name, count(rental_id) as total_films_rented
from customer c
join rental r using (customer_id)
group by full_name;

----------------------------------------------------------------------------------------------------------------
--- List of Films and Categories
select title, name
from film f
join film_category fc using (film_id)
join category c using (category_id);

----------------------------------------------------------------------------------------------------------------
--- Number of films available for each category
select name, count(film_id) as available_films
from category c 
join film_category fc using (category_id)
join film f using (film_id)
group by name;

----------------------------------------------------------------------------------------------------------------
--- Revenue Generated by Each Film
select title,sum(p.amount) as revenue
from film 
join inventory i using (film_id)
join rental r using (inventory_id)
join payment p using (rental_id)
group by title;

----------------------------------------------------------------------------------------------------------------
--- Top 5 Customers by Rentals
select concat(first_name,' ',last_name) as full_name, sum(p.amount) as total_spent
from customer c
join rental r using (customer_id)
join payment p using (rental_id)
group by full_name
order by total_spent desc
limit 5;

---------------------------------------------------------------------------------------------------------------
--- Most Rented film and Number of Times it was Rented
select title, count(rental_id) as rental_count
from film f
join inventory i using (film_id)
join rental r using (inventory_id)
group by title 
order by rental_count desc
limit 1;

---------------------------------------------------------------------------------------------------------------
--- Category with the highest Revenue
select name, sum(amount) as total_revenue
from category c
join film_category fc using (category_id)
join film f using (film_id)
join inventory i using (film_id)
join rental r using (inventory_id)
join payment p using (rental_id)
group by name 
order by total_revenue desc
limit 1;

---------------------------------------------------------------------------------------------------------------
--- Average Rental Duration for Each film category
select name, round(avg(rental_duration), 2) as average_rental_duration
from category c
join film_category fc using (category_id)
join film f using (film_id)
group by name

---------------------------------------------------------------------------------------------------------------
--- Number of Customers in each city
select city, count(customer_id) as customer_count
from city c
join address a using (city_id)
join customer cu using (address_id)
group by city
order by customer_count desc;

---------------------------------------------------------------------------------------------------------------
--- Staff Member with the Most Revenue
select concat(first_name,' ',last_name) as full_name, sum(p.amount) as total_revenue
from staff s
join payment p using (staff_id)
group by full_name
order by total_revenue desc
limit 1;

---------------------------------------------------------------------------------------------------------------
--- Customers who have Rented films in more than one City
select concat(first_name,' ',last_name) as full_name
from customer c
join address using (address_id)
join city ci using (city_id)
group by full_name
having count(distinct city) > 1;

---------------------------------------------------------------------------------------------------------------
--- Most Rented Category
select name, count(rental_id) as rental_count
from category c
join film_category fc using (category_id)
join film f using (film_id)
join inventory i using (film_id)
join rental r using (inventory_id)
group by name
order by rental_count desc
limit 1;

---------------------------------------------------------------------------------------------------------------
--- Total Revenue for each store
select store_id, sum(amount) as total_revenue
from store s
join staff st using (store_id)
join payment p using (staff_id)
group by store_id
order by total_revenue desc;

--------------------------------------------------------------------------------------------------------------
--- Total number of Films Rented per Month
select to_char(rental_date, 'Month') as rental_month,count(rental_id) as total_films_rented
from rental
group by rental_month
order by total_films_rented desc;











